package com.scenevibe.tvcompanionpoc;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.HexFormat;
import static org.junit.Assert.*;

/**
 * Consumes the exact Cloud-produced bytes and shared corpus exported by #19.
 * No assignment fixture is independently authored here. The digest binds the
 * corpus to its producer record; an optional directory supports live exports
 * from both checkouts without committing private FinalTrack text.
 */
public final class M1CloudInteropTest {
    /** Read generated bytes from the harness directory or its pinned CI snapshot. */
    private static byte[] bytes(String name) throws Exception {
        String directory=System.getenv("SCENEVIBE_M1_FIXTURES");
        if(directory!=null)return Files.readAllBytes(Path.of(directory,name));
        try(InputStream stream=M1CloudInteropTest.class.getResourceAsStream("/m1/"+name)) {
            if(stream==null)throw new IllegalStateException("M1 fixture missing");
            return stream.readAllBytes();
        }
    }

    /** Decode only the already bounded test artifacts as JSON. */
    private static JSONObject json(String name) throws Exception {
        return new JSONObject(new String(bytes(name),StandardCharsets.UTF_8));
    }

    /** Verify every declared accept/reject case against the production TV parser. */
    @Test public void sharedCorpusMatchesJava() throws Exception {
        byte[] corpus=bytes("overlay-corpus.json");
        String digest=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(corpus));
        assertEquals(json("cloud-envelopes.json").getString("corpusSha256"),digest);
        JSONArray cases=new JSONObject(new String(corpus,StandardCharsets.UTF_8)).getJSONArray("cases");
        for(int index=0;index<cases.length();index++) {
            JSONObject fixture=cases.getJSONObject(index);
            boolean accepted;
            try {
                OverlayManifestParser.parse(fixture.getJSONObject("manifest"));
                accepted=true;
            } catch(OverlayManifestParser.Invalid invalid) {accepted=false;}
            assertEquals(fixture.getString("name"),fixture.getBoolean("runtimeValid"),accepted);
        }
        System.out.println("M1 Java shared corpus: "+cases.length()+" cases");
    }

    /** Exercise the exact Cloud envelope, runtime parser and cross-contract bridge. */
    @Test public void productionCloudEnvelopesAreInstallable() throws Exception {
        JSONObject producer=json("cloud-envelopes.json");
        assertEquals("pierre22400/interface-scenevibe",producer.getString("sourceRepository"));
        assertEquals(3,producer.getJSONArray("producerFiles").length());
        JSONArray cases=producer.getJSONArray("cases");
        for(int index=0;index<cases.length();index++) {
            JSONObject fixture=cases.getJSONObject(index);
            JSONObject envelope=fixture.getJSONObject("envelope");
            assertTrue(fixture.getString("name"),CloudProtocol.validAssignment(
                    envelope,envelope.getString("deviceId"),0));
            ScheduledTrack runtime=TrackParser.parse(envelope.getJSONObject("runtimeTrack"),media->null);
            if(envelope.has("overlayManifest")) {
                assertEquals("overlay-manifest-v1",envelope.getString("visualMode"));
                OverlayManifest manifest=OverlayManifestParser.parse(envelope.getJSONObject("overlayManifest"));
                assertTrue(fixture.getString("name"),VideoOverlayManifestBridge.validate(runtime,manifest).ok);
                assertEquals("freeze",manifest.pauseBehavior);
            } else {
                assertEquals("legacy-v1",envelope.getString("visualMode"));
                assertEquals("VIDEO_V1_NOT_REPRESENTABLE",envelope.getString("manifestFallbackReason"));
            }
        }
        System.out.println("M1 Cloud -> Java envelopes: "+cases.length()+" cases");
    }

    /** Optional private Columbo rehearsal; editorial text never enters this repo. */
    @Test public void originalColumboProjectionIsInstallable() throws Exception {
        String directory=System.getenv("SCENEVIBE_M1_SONY_FIXTURES");
        org.junit.Assume.assumeTrue(directory!=null);
        JSONObject artifact=new JSONObject(Files.readString(Path.of(directory,"cloud-envelopes.json")));
        JSONObject envelope=artifact.getJSONArray("cases").getJSONObject(0).getJSONObject("envelope");
        assertTrue(CloudProtocol.validAssignment(envelope,envelope.getString("deviceId"),0));
        ScheduledTrack runtime=TrackParser.parse(envelope.getJSONObject("runtimeTrack"),media->null);
        OverlayManifest manifest=OverlayManifestParser.parse(envelope.getJSONObject("overlayManifest"));
        assertEquals("finaltrack-04527f84a0e48668fdba3c2b",runtime.trackId);
        assertEquals(16,runtime.comments.size());
        assertEquals(16,manifest.scenes.size());
        assertTrue(VideoOverlayManifestBridge.validate(runtime,manifest).ok);
        assertFalse(envelope.getJSONObject("overlayManifest").toString().contains("\"type\":\"image\""));
        System.out.println("M1 original Columbo -> Java: 16 scenes; offline rehearsal only");
    }
}
